{
 "title": "Categorization Model Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total{handler=\"/v1/categorize\"}[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/v1/categorize\"}[10s])",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "HTTP Success Rate (30m avg)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status!=\"5xx\"}[30m])) / sum(rate(http_requests_total[30m]))"
    }
   ]
  },
  {
   "title": "Prediction Categories (10m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(rate(product_classifier_output_total[10m]))\n/ ignoring(category) group_left\nsum without (category, categories)(rate(product_classifier_output_total[10m])) * 100",
     "legendFormat": "{{ category }}"
    }
   ]
  },
  {
   "title": "Request size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_size_bytes_sum{handler=\"/v1/categorize\"}[1m])) / sum(rate(http_request_size_bytes_count{handler=\"/v1/categorize\"}[1m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"my-application\",handler!=\"none\"} / http_request_duration_seconds_count",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "  rate(process_cpu_seconds_total{job=\"my-application\"}[30s])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"my-application\"}",
     "legendFormat": "mem"
    }
   ]
  }
 ]
}