name: Test

on: [push, pull_request]

jobs:
  autoflake:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9.1
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.1
      
      - name: Install autoflake
        run: pip install autoflake==1.4

      - name: Run autoflake
        run: autoflake server/*.py

  isort:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9.1
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.1
      
      - name: Install isort
        run: pip install isort==5.7.0

      - name: Run isort
        run: isort server

  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9.1
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.1
      
      - name: Install black
        run: pip install black==20.8b1

      - name: Run black
        run: black server


  pytest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9.1
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.1
        
      - name: Install dependencies
        run: pip install -r server/requirements.txt

      - name: Run tests
        working-directory: ./server
        run: pytest
